# Generated by Django 2.0.1 on 2018-01-29 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20180129_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
    ]
