# Generated by Django 2.0.1 on 2018-01-29 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20180129_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('amount', models.CharField(max_length=64)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricings', to='payments.Payment')),
            ],
        ),
    ]
