# Generated by Django 2.0.1 on 2018-01-29 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='payments.Payment'),
        ),
    ]
