# Generated by Django 2.0.1 on 2018-01-30 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0005_auto_20180129_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionPaypal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl_receiver_email', models.CharField(max_length=64)),
                ('pl_receiver_id', models.CharField(max_length=64)),
                ('pl_txn_id', models.CharField(max_length=64)),
                ('pl_txn_type', models.CharField(max_length=64)),
                ('pl_payer_email', models.CharField(max_length=64)),
                ('pl_payer_id', models.CharField(max_length=64)),
                ('pl_payer_status', models.CharField(max_length=64)),
                ('pl_first_name', models.CharField(max_length=64)),
                ('pl_last_name', models.CharField(max_length=64)),
                ('pl_address_city', models.CharField(max_length=64)),
                ('pl_address_country', models.CharField(max_length=64)),
                ('pl_address_status', models.CharField(max_length=64)),
                ('pl_address_country_code', models.CharField(max_length=64)),
                ('pl_address_name', models.CharField(max_length=64)),
                ('pl_address_street', models.CharField(max_length=64)),
                ('pl_address_zip', models.CharField(max_length=64)),
                ('pl_custom', models.CharField(max_length=64)),
                ('pl_handling_amount', models.CharField(max_length=64)),
                ('pl_item_name', models.CharField(max_length=64)),
                ('pl_item_number', models.CharField(max_length=64)),
                ('pl_mc_currency', models.CharField(max_length=64)),
                ('pl_mc_fee', models.CharField(max_length=64)),
                ('pl_mc_gross', models.CharField(max_length=64)),
                ('pl_payment_date', models.CharField(max_length=64)),
                ('pl_payment_fee', models.CharField(max_length=64)),
                ('pl_payment_gross', models.CharField(max_length=64)),
                ('pl_payment_status', models.CharField(max_length=64)),
                ('pl_payment_type', models.CharField(max_length=64)),
                ('pl_protection_eligibility', models.CharField(max_length=64)),
                ('pl_quantity', models.CharField(max_length=64)),
                ('pl_shipping', models.CharField(max_length=64)),
                ('pl_tax', models.CharField(max_length=64)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactionpaypal', to=settings.AUTH_USER_MODEL)),
                ('pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactionpaypal', to='payments.Pricing')),
            ],
        ),
    ]
