# Generated by Django 2.0.1 on 2018-01-30 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_transactionpaypal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionpaypal',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactionpl', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transactionpaypal',
            name='pricing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactionpl', to='payments.Pricing'),
        ),
    ]
