# Generated by Django 2.0.2 on 2018-02-08 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_event_vender'),
        ('payments', '0008_transactionpaypal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionpaypal',
            name='event',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='transactionpl', to='events.Event'),
            preserve_default=False,
        ),
    ]
