# Generated by Django 2.0 on 2017-12-27 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='updated',
        ),
    ]
