# Generated by Django 2.0 on 2017-12-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20171229_1456'),
        ('profiles', '0002_auto_20171227_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='categories',
            field=models.ManyToManyField(blank=True, to='events.Category'),
        ),
    ]
