# Generated by Django 2.0 on 2018-01-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='teacher',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
