# Generated by Django 2.0.1 on 2018-01-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='profile_list/'),
        ),
    ]
