# Generated by Django 2.0.1 on 2018-01-07 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_category_image'),
        ('profiles', '0012_auto_20180105_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.ManyToManyField(blank=True, to='events.Category')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='teacher_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Teacher'),
        ),
    ]
