# Generated by Django 2.0.1 on 2018-01-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_category_image'),
        ('profiles', '0013_auto_20180107_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='teacher_info',
        ),
        migrations.AddField(
            model_name='profile',
            name='teacher_categories',
            field=models.ManyToManyField(blank=True, related_name='teaching', to='events.Category'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='categories', to='events.Category'),
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
