# Generated by Django 2.0.1 on 2018-01-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_category_image'),
        ('profiles', '0014_auto_20180107_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='events',
            field=models.ManyToManyField(blank=True, to='events.Event'),
        ),
    ]
