# Generated by Django 2.0.1 on 2018-01-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_profile_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='events.Event'),
        ),
    ]
