# Generated by Django 2.0 on 2018-01-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_short',
            field=models.TextField(blank=True, null=True),
        ),
    ]
