# Generated by Django 2.0 on 2018-01-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_category_description_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('event', 'event'), ('festival', 'festival')], default='event', max_length=30),
            preserve_default=False,
        ),
    ]
