# Generated by Django 2.0.1 on 2018-01-05 07:27

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=events.models.OverwriteStorage(), upload_to=events.models.event_name_path),
        ),
    ]
