# Generated by Django 2.0.1 on 2018-01-05 08:42

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=events.models.OverwriteStorage(), upload_to=events.models.category_name_path),
        ),
    ]
