# Generated by Django 2.0.1 on 2018-01-23 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venders', '0001_initial'),
        ('events', '0017_auto_20180112_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='vender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='venders.Vender'),
            preserve_default=False,
        ),
    ]
