# Generated by Django 2.0.1 on 2018-01-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_auto_20180117_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
