# Generated by Django 2.0.1 on 2018-01-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_friend_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
