# Generated by Django 2.0.1 on 2018-01-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_friend_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.CharField(choices=[('requested', 'requested'), ('friend', 'friend'), ('blocked', 'blocked')], max_length=50),
        ),
    ]
